version: "3.8"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www
    ports:
      - "3003:3003"
    command: php artisan serve --host=0.0.0.0 --port=3003
